# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\x12\tembedding\" \n\x10\x45mbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"9\n\x11\x45mbeddingResponse\x12\x11\n\tdimension\x18\x01 \x01(\x05\x12\x11\n\tembedding\x18\x02 \x03(\x02\"&\n\x15\x45mbeddingBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"J\n\x16\x45mbeddingBatchResponse\x12\x30\n\nembeddings\x18\x01 \x03(\x0b\x32\x1c.embedding.EmbeddingResponse2\xc1\x01\n\x10\x45mbeddingService\x12P\n\x11GenerateEmbedding\x12\x1b.embedding.EmbeddingRequest\x1a\x1c.embedding.EmbeddingResponse\"\x00\x12[\n\x12GenerateEmbeddings\x12 .embedding.EmbeddingBatchRequest\x1a!.embedding.EmbeddingBatchResponse\"\x00\x42-\n\x19\x63om.luontd.grpc.embeddingB\x0e\x45mbeddingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.luontd.grpc.embeddingB\016EmbeddingProtoP\001'
  _globals['_EMBEDDINGREQUEST']._serialized_start=30
  _globals['_EMBEDDINGREQUEST']._serialized_end=62
  _globals['_EMBEDDINGRESPONSE']._serialized_start=64
  _globals['_EMBEDDINGRESPONSE']._serialized_end=121
  _globals['_EMBEDDINGBATCHREQUEST']._serialized_start=123
  _globals['_EMBEDDINGBATCHREQUEST']._serialized_end=161
  _globals['_EMBEDDINGBATCHRESPONSE']._serialized_start=163
  _globals['_EMBEDDINGBATCHRESPONSE']._serialized_end=237
  _globals['_EMBEDDINGSERVICE']._serialized_start=240
  _globals['_EMBEDDINGSERVICE']._serialized_end=433
# @@protoc_insertion_point(module_scope)
